import { STELLAR_NETWORK_PASSPHRASE, STELLAR_RPC_URL } from '@/lib/stellar/config'
import { getNativeAssetContractAddress, getSplitRouterContractAddress } from '@/lib/config'

// Type shim: actual package is generated by scaffold after build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { Client as SplitRouterClient } from 'split_router'

type Signer = (xdr: string) => Promise<string>

export async function executeSplit(params: {
  publicKey: string
  signTransaction: Signer
  recipients: { address: string; shareBps: number }[]
  amount: bigint
  tokenContractId?: string
}) {
  const { publicKey, signTransaction, recipients, amount } = params
  const token = params.tokenContractId ?? getNativeAssetContractAddress()
  const contractId = getSplitRouterContractAddress()
  if (!contractId) throw new Error('Split Router contract not configured')

  const client = new SplitRouterClient({
    contractId,
    rpcUrl: STELLAR_RPC_URL,
    networkPassphrase: STELLAR_NETWORK_PASSPHRASE,
    publicKey,
    signTransaction
  })

  const to = recipients.map(r => r.address)
  const bps = recipients.map(r => Math.floor(r.shareBps))

  const tx = await client.split({ token, payer: publicKey, recipients: to, shares_bps: bps, amount })
  const { result } = await tx.signAndSend()
  return result
}

